# fly.toml app configuration file generated for fastrepl on 2024-06-25T17:02:24+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "canary-prod"
primary_region = "sjc"
kill_signal = "SIGTERM"
kill_timeout = 120

[build]
  dockerfile = "Dockerfile"

[env]
  PHX_HOST = "cloud.getcanary.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/health"
  timeout = "5s"

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2
